### ISSUE TITLE
The 'share' icon shouldn't copy the URL without warning

### ISSUE THREAD

**Issue by mialondon** [LibCrowds/project-iiif-annotate#34]
This could cause information loss if people had something else they wanted to keep in their buffer. The UV has a model for sharing URLs that might work, if only for consistency between BL projects.

**Comment by alexandermendes** [comment]
Well there is a tooltip that comes up when you hover over the button saying "Copy URL", and clicking on it does so. So not entirely without warning and the kind of thing I've seen in many other places! Making people copy it from a text input is usually used because it's easier than copying automatically with JavaScript and probably provides better compatibility for IE6 or whatever. But we can look at updating this later.

**Comment by alexandermendes** [comment]
This issue was moved to LibCrowds/libcrowds-viewer#107
