### ISSUE TITLE
Add video/screencast to the long description

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/project-iiif-annotate#7]

**Comment by mialondon** [comment]
Thinking about it, animated gifs might be the best way to do this - they can be included in help and tutorial pages with auto-play on so that people absorb things like 'how to draw a rectangle and save it' or 'what text to transcribe'. The format will also make us be disciplined in how long they can be, which'll be much more user-friendly.

**Comment by alexandermendes** [comment]
I suppose this is a part of https://github.com/LibCrowds/project-playbills/issues/11

We now have a way of doing this via Markdown blocks in the help files
